### ISSUE TITLE
pagination / bookpagination?

### ISSUE THREAD

**Issue by wujastyk** [maieul/biblatex-manuscripts-philology#10]
From the documentation, it is not clear to me what "pagination" is for. Is it as in the Biblatex manual, affecting postnote formatting, etc?

**Comment by maieul** [comment]
Yes. Precisly.

That here that you must tell to use "folio" as unit (cf #8). To make it clear, maybe we could:
- reformulate the explanation for the fields (but for me, it is clear... if you know biblatex working.... and I don't think my handbook should substitute general biblatex handbook)
- add a subsection "set up to folio" or something like this, in the "use" section.

**Comment by wujastyk** [comment]
I made some edits to the documentation in my Git fork (and made a pull request). I hope this addresses this point adequately.
