### ISSUE TITLE
Italian localization not working

### ISSUE THREAD

**Issue by Doc73** [maieul/biblatex-manuscripts-philology#13]
I have seen that there are many developments on this package and therefore I propose this issue in italian (at least) localization.

Here is a MWE:
```
% !TeX program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT

\begin{filecontents}{bibliography.bib}
@manuscript{Vatgr1,
  collection     = {Vaticanus graecus},
  location       = {Città del Vaticano},
  library        = {Bibliotheca Apostolica Vaticana},
  shelfmark      = {1},
  bookpagination = {folio},
  columns        = {1},
  dating         = {X saec.},
  shortlibrary   = {Vat.},
  pagetotal      = {300},
  shorthand      = {O},
  support        = {pergament},
  keywords       = {manuscripti},
}

@manuscript{Pargr1807,
  collection     = {Parisinus Graecus},
  location       = {Paris},
  library        = {Bibliothèque Nationale de France},
  shelfmark      = {1807},
  bookpagination = {folio},
  columns        = {2},
  dating         = {IX saec.},
  shortlibrary   = {Par.},
  pagetotal      = {300},
  shorthand      = {A},
  support        = {pergament},
  keywords       = {manuscripti},
}

@manuscript{Beinecke278,
  collection = {Beinecke},
  location   = {New Haven (Connecticut)},
  library    = {Yale University},
  shelfmark  = {278},
  columns    = {2},
  dating     = {4 October 1453},
  pages      = {1\recto--160\recto},
  pagetotal  = {164},
  pagination = {column},
  support    = {paper},
  annotation = {Written in Italy by Ioannes Skoutariotes in 1453 (see Vogel and Gardthausen, pp. 197-99; Canart, p. 68; de Meyier, p. 262). Acquired from Frater Philippus Lapaccinus by the Dominican convent of San Marco in Florence in the 15th century; ownership inscription of 15th century on f. ii verso is partially erased but still legible under ultraviolet light: "Iste liber est conuentus Sancti Marci de Florentia ordinis predicatorum. In bancho vj occidentis librarie grece. Habitus a fratre philippo lapaccino filio natiuo. N. LXXXVIIII." (B. Ullman and P. Stadter, The Public Library of Renaissance Florence [Padua, 1972] pp. 76, n. 1; 264; 279; 317.) Collection of Sir Thomas Phillipps (no. 10371, on spine), who purchased it from Payne (Cat. 1835, no. 100). Acquired in 1953 by Thomas E. Marston (bookplate) from C. A. Stonehill. Gift of Thomas E. Marston in 1959.},
  shorthand      = {B},
  keywords   = {manuscripti},
  origin     = {Italy},
  scribe     = {Ioannes Skoutariotes},
}
\end{filecontents}

\documentclass{article}
\usepackage{filecontents}

\usepackage{polyglossia}
	\setmainlanguage{italian}
\usepackage{libertinus-otf}

\usepackage[
	backend=biber,%
	language=italian,%
	autolang=other,%
	bibstyle=manuscripts-noautoshorthand,
	]{biblatex}
\addbibresource{biblio.bib}

\begin{document}
\cite{Vatgr1}

%\shcite{Vatgr1}

\nocite{*}
\printshorthands[type=manuscript,title=Conspectus siglorum]

\printshorthands[type=manuscript,env=details,title=Description of manuscripts]
\end{document}
```
As you can see, some words remains in english and are in bold typeface. Log file says: `Package biblatex Warning: Bibliography string 'pergament' undefined`

OT: what do you think about a latin localization?

**Comment by wujastyk** [comment]
I think a Latin localization would be great!  Maybe I should do a Sanskrit one.  (But I don't have time right now.)

I compiled your MWE and got the attached PDF image.  It looks great, but my compile shows some small residual spacing problems ("2column" etc.).
![screenshot from 2018-09-18 15-00-54](https://user-images.githubusercontent.com/762246/45716310-c9f8b700-bb53-11e8-8780-f95d18780918.png)

**Comment by Doc73** [comment]
Yes, these are the issues I report

**Comment by Doc73** [comment]
I would expect 

> 1 colonna

and NOT 

> 1**column**

etc.

**Comment by maieul** [comment]
please check branch issue13. 
for the latin: why not. The priority is, however, to add the two new support to italian translation.

**Comment by Doc73** [comment]
I can't find branch issue13...

**Comment by maieul** [comment]
Should be here now.

**Comment by Doc73** [comment]
It's working, but
1. the words in bold are wanted?
2. the output produces abbreviated words: are they wanted? Is it possible to change them in regular font?

Other remarks: 
1. there are incorrect words;
2. there is a mixture of Italian forms and Latin forms.
I'll try to change them via github.

**Comment by maieul** [comment]
1. Yes, word in bold are wanted. You can change that by a redefinition of `\mkmanuscriptdescriptionlabel` and `\mkmanuscriptdescriptionlabelparagraphed` as explained in the handbook.
2. As usually, biblatex allow to use abbreviated or full form of word. Thats is the option `abbreviate` when loading the package (default=true)

Other remarks: I don't remember who send me this italian translation. In french, we can mix french and latin word, as some latin word are present *tels quels* in French.
