### ISSUE TITLE
Doc typo

### ISSUE THREAD

**Issue by Doc73** [maieul/biblatex-manuscripts-philology#4]
§ 3.4
`\printshorthand[type=manuscript,env=details,title=Description of manuscripts]`
instead of
`\printshorthands[type=manuscript,env=details,title=Description of manuscripts]`

Off-Topic 1
Your package must be loaded by `bibstyle`, but it is unclear whether it is incompatible with other bibliographic styles, such as `authortitle`.

Off-Topic 2
I attach an italian/latin localization. :-)
[italian-manuscripts.lbx.txt](https://github.com/maieul/biblatex-manuscripts-philology/files/124556/italian-manuscripts.lbx.txt)

**Comment by maieul** [comment]
Thanks for the typo corrected on e9da15e.

"Off-Topic 1": bibstyle loaded by default is verbose, which calls authortitle. But if you need other style, use biblatex-multiple-dm. Cf 015d6bc.

Thanks also for italian. Cf eadaf2f. 

Please tell me if § are not clear.

**Comment by Doc73** [comment]
Therefore, have I to load the packages in this way?
```tex
\usepackage[tools={manuscripts},bibstyle=authortitle]{biblatex-multiple-dm}
\usepackage[bibstyle=multiple-dm,citestyle=authoryear]{biblatex}
```
Sorry, but the manual is not clear to me

**Comment by maieul** [comment]
as explained, 

`\usepackage[bibstyle=manuscripts,otheroption�]{biblatex}` 

will load the "verbose" style, which already load "authortitle".

biblatex-multiple-dm is need only if you need other bibliographic style than verbose or authortitle.

**Comment by Doc73** [comment]
Yes, sure!
I asked because, in general, I like other bibstyle (`authortitle`) and citestyle (`authoryear`), and I would use `verbose` only for mss.

Ah! A suggestion!

Because it is do easy to add a personal localization, why don't add a chapter in doc with some infos?

You could copy a sample file (in english), explain that the new document should be placed in the folder of our tex file, and clarify that in our preamble must be added the string
`\DeclareLanguageMapping{<lang>}{<lang>-manuscript}`

**Comment by maieul** [comment]
verbose bibstyle call authortitle bibstyle.

Cf verbose.bbx file

````
\ProvidesFile{verbose.bbx}
[\abx@bbxid]

\RequireBibliographyStyle{authortitle}

\endinput
````

For localisation
1) it is a general feature of biblatex.
2) I prefer people doing like you and send me the localiszation file, in order to share them in distribution.

**Comment by Doc73** [comment]
Ok! It is important, for me, that this package doesn't affect `citestyle`. :-)

Thank you very much!!!

**Comment by maieul** [comment]
ok, but what should be citestyle=authoryear for anonymous and not dated manuscripts ?
cf 3a44e82

**Comment by Doc73** [comment]
No, no!
I thougt at my book, in which there are many different bibliographies, but only one is my bib file.
So, I would cite a ms according your packages, but articles etc. according another citestyle.

**Comment by maieul** [comment]
yes, it is possible, I have just clarify the handbook.

**Comment by Doc73** [comment]
:+1:
