### ISSUE TITLE
some Sanskrit-related desiderata

### ISSUE THREAD

**Issue by wujastyk** [maieul/biblatex-manuscripts-philology#5]
Dear Maïeul,

I have been trying out your valuable biblatex-manuscripts-philology package with a view to a small project.  I deal with Sanskrit manuscripts mainly, and I would like to add a few details and options to your package.  But biblatex programming is complex, and I have not spent enough time to do what I want easily.

Here are some features I'd like to add:
1. A field for script (to include Devanāgarī, Śāradā, Bengali, and others)
2. Additional support types, including palm-leaf and birch-bark.
3. The inclusion of the field Contents in the output format of the MS description. I would like to express some of the content of the MS (e.g., 'Contains such-and-such text, chapter 3, verses 2-5') separately from the Annotations.

These are the main changes at present, though if you are willing to contemplate new features, I would maybe have a few more.
Many thanks,
Dominik

**Comment by maieul** [comment]
Dear Dominik,

I think it should be quite easy to implement that. However I need some precision
1. We are ok that script are different than alphabet. For example, in latin world, we have latin alphabet, but "Carolin" and "Gothic" script (and other ones)?
2. In any case, in which position do you want to print the script
3. Should we define any key value 
4. For additionnal support script, it should be ok with key-value.
5. Idem, for contents field, I suppose it would be only for env=details bibliography.

**Comment by maieul** [comment]
By the way : please next time open one "issue" by problem.

**Comment by wujastyk** [comment]
On Tue, 4 Sep 2018 at 02:07, Maïeul Rouquette <notifications@github.com>
wrote:

> Dear Dominik,
>
> I think it should be quite easy to implement that. However I need some
> precision
>
>    1. We are ok that script are different than alphabet. For example, in
>    latin world, we have latin alphabet, but "Carolin" and "Gothic" script (and
>    other ones)?
>
> I meant different "writing systems."  E.g., Greek and Cyrillic.  I think
this is what you mean by alphabet, although in India most scripts are
syllabic, not alphabetic.  In the Indian case, there are about fourteen
major writing systems used on the subcontinent, and more if you include
derived scripts of South East Asia.  See these lists and charts
<https://en.wikipedia.org/wiki/Brahmic_scripts#List_of_Brahmic_scripts>.  I
do not mean script.


>    1. In any case, in which position do you want to print the script
>
> Hmm.  Probably next to the other elements of physical description, like
support and foliation.


>
>    1. Should we define any key value
>
> I think not.  Users will only complain that the key list isn't quite
right, or doesn't include their particular writing system, etc.  I think a
simple text string field is best.


>
>    1. For additionnal support script, it should be ok with key-value.
>
> Yes, for India, in addition to "paper", the most common supports include
"birch bark" and "palm leaf."

>
>    1. Idem, for contents field, I suppose it would be only for
>    env=details bibliography.
>
> Yes, env=details only.


>
>
> Thanks!

**Comment by maieul** [comment]
So, you think script would be to good term? And what about the subset of script like in my case Caroline vs Gothic.

I key system could be implemented with some commands to allow user to create their own keys. The advantage would be in terme of automatic abbreviation, uniformization and so on.

**Comment by wujastyk** [comment]
The palaeographical study of Indian writing systems is not yet developed
enough to have a standard set of names for different writing styles.  And
if we leave the "writing system" field as plain text, without key value,
people can always make up their own mind (e.g., "Jaina Nāgarī," "Nandi
Nāgarī," etc.)

But if the key system can be easily extended as you say, then yes, I think
it would be very helpful and would help with standardization.  So, yes! :-)

--
Professor Dominik Wujastyk <http://ualberta.academia.edu/DominikWujastyk>
,

Singhmar Chair in Classical Indian Society and Polity
,

Department of History and Classics <http://historyandclassics.ualberta.ca/>
,
University of Alberta, Canada
.

South Asia at the U of A:

sas.ualberta.ca

**Comment by maieul** [comment]
@Doc73 I will need italien translation for:
 - "Content"
- "Remark"
- "palm-leaf"
- "birch-bark"

Could you provide it?

**Comment by maieul** [comment]
@doc73 : for "palm-leaf" and "bich-bark", I need also abbreviated form.

**Comment by maieul** [comment]
- [ ] Additionnal Support
- [ ] Script 
- [ ] Content

**Comment by Doc73** [comment]
- contenuto
- osservazione (plur. osservazioni)

I think "birch-bark" is "carta cinese", according to M. Maniaci, _Terminologia del libro manoscritto_, Préface di Denis Muzerelle, Toma 1996, p. 42.
As for "Palm leaf", Ead. p. 22 record "palma" between "organical supports". Therefore, I would translate it as "foglia di palma".
Maniace doesn't  record abbreviations for these words, but later I'll look for it in AA. VV., _Comparative Oriental Manuscript Studies. An Introduction_, Hamburg 2015.

**Comment by Doc73** [comment]
I think that Maieul refers to this file (italian localization): https://github.com/maieul/biblatex-manuscripts-philology/blob/master/italian-manuscripts.lbx

I don't know exactly what is "birch-bark", but Marilena Maniaci uses the terms "carta orientale". If "birch-bark" **is** "carta orientale", it's well, otherwise please explain me better what "birch-bark" is and the I'll try to find some words for italian localization, according to the habits of classifications in Italian libraries codified by Marilena Maniaci, a very well-known Italian palaeographer and codicologist whom I had the honor to know.

**Comment by wujastyk** [comment]
Did the articles by me and by Sathaye that I attached to the last email get
through?  They explain birch bark and palm leaf, and Sathaye has a nice
photo of birch bark.  Neither can be "carta orientale".  Birch bark is
literally sheets of the bark of the birch tree.  It was also used
extensively for early Russian manuscripts.  Plenty of photos an notes in this
Google search <https://www.google.com/search?q=birch+bark+manuscript>.
Here is a poorly-preserved birch bark MS at archive.org
<https://archive.org/details/BirchBarkVedicCommentariesSharadaRSktSJammuNo40>
.

--
Professor Dominik Wujastyk <http://ualberta.academia.edu/DominikWujastyk>
,

Singhmar Chair in Classical Indian Society and Polity
,

Department of History and Classics <http://historyandclassics.ualberta.ca/>
,
University of Alberta, Canada
.

South Asia at the U of A:

sas.ualberta.ca

**Comment by Doc73** [comment]
@wujastyk 
Ah, ok!
Then we can translate it "carta di corteccia di betulla" or "carta di betulla"? Do you think it's okay?

**Comment by Doc73** [comment]
Yes, sure! But consider I'm not the developer of Italian translation and therefore all suggestions of other people is welcome, especially in fields that are not mine. 😊

**Comment by maieul** [comment]
@wujastyk I have completed all your request. Could you please try the branch "issue 5".

Attached is the prototype of the new version of handbook. Especially, it explains how to add your own pairs of key-value. Could you look into it, also for the presentation of script field?
[biblatex-manuscripts-philology.pdf](https://github.com/maieul/biblatex-manuscripts-philology/files/2386821/biblatex-manuscripts-philology.pdf)


I have translated into French  "birch-bark" and "palm-leaf" for the french language file. But if you have an french speaker expert in Indian manuscripts, it could be better

@Doc73  and @wujastyk I wait for a definitive translation before adding it to italian. However, I would like to release with the translation. 

@wujastyk  if you answer by email, you can't send files. You need to use github web interface to do it.

**Comment by wujastyk** [comment]
Here are links to the articles I mentioned in an email reply a day ago, that didn't get through:

- https://www.dropbox.com/s/4fuexnvhgt2ppy8/2013%20Indian%20Manuscripts.pdf?dl=0
- https://www.dropbox.com/s/8fnk2chw0aqnguq/2016%20The%20public%20life%20of%20manuscripts.pdf?dl=0

**Comment by wujastyk** [comment]
I've tried to test the issue5 release but I'm stuck because I'm too ignorant :-)

1. I can't compile biblatex-manuscripts-philology.tex; although I installed Pigments, which was the first problem, I still can't get a PDF because dvipdfmx throws an error.  

> xdvipdfmx:fatal:  This font using the "seac" command for accented characters...
>
> Output file removed.
> (see the transcript file for additional information)
> Error 256 (driver return code) generating output;
> file biblatex-manuscripts-philology.pdf may not be valid.
> Transcript written on biblatex-manuscripts-philology.log.


[biblatex-manuscripts-philology.log](https://github.com/maieul/biblatex-manuscripts-philology/files/2386937/biblatex-manuscripts-philology.log)

2. I don't know how to get JabRef to "see" the new fields available for support.

I have run texhash.

See attached log file.

**Comment by maieul** [comment]
1. You don't need to run the .tex file, it is only to produce the PDF and I send it to you. When I will send it to the CTAN, the handbook will be available. I don't know exactly where comes your problem, it is strange but priority. Just put the biblatex-manuscripts-philology directory in your personal texmf directory.
2. https://help.jabref.org/en/CustomEntryTypes

**Comment by wujastyk** [comment]
On Sun, 16 Sep 2018 at 13:55, Maïeul Rouquette <notifications@github.com>
wrote:

>
>    1. ... Just put the biblatex-manuscripts-philology directory in your
>    personal texmf directory.
>
> Yes, I already did that, and remembered to run texhash.  Don't worry, I'll
work out the JabRef issue.

The manual says one can use Content instead of Annotation.  Can one use
both?

I think all is well now.
Best,
Dominik

**Comment by maieul** [comment]
yes, it is cumulative. Do you think I should rewrite the handbook?

**Comment by wujastyk** [comment]
Dear Maïeul, I've forked the repo and I'll make some edits to the manual
and issue a pull request.  If you wish, you can consider my edits for the
main release.

Best,
Dominik

**Comment by wujastyk** [comment]
"Contents" is the normal expression in current English for items in a book or manuscript. So, also, "The Contents Page" etc. etc.

**Comment by maieul** [comment]
I have just change to contents in branch 2.0

**Comment by maieul** [comment]
So 
@wujastyk after your correction, all should be ok. Could you please check a last time on branch 2.0  before I make the release?
@wujastyk and @Doc73 for release, I just need final terms for the two new supports.

**Comment by wujastyk** [comment]
The English versions of the new supports should not be hyphenated: the correct forms are "palm leaf" and "birch bark"  (not palm-leaf, birch-bark or palmleaf, birchbark).

**Comment by wujastyk** [comment]
I say publish 2.0.  Thanks!

**Comment by maieul** [comment]
As it is a key-value system, the key is hyphenated, but not the value

**Comment by maieul** [comment]
so, before releasing, I need @Doc73 italian translation for palmleaf and birchbark.

**Comment by Doc73** [comment]
I can only suggest:

- birch bark: carta di corteccia <di betulla?>
- palmleaf: carta di foglia di palma _or_ foglia di palma

But I think it is better to hear the opinion of an expert in this field.

**Comment by wujastyk** [comment]
I may be the wrong person, but may I suggest 

- palm leaf = **foglia di palma** (see, e.g., this [usage](https://copernicum.it/book/antico-libro-in-foglia-di-palma-manoscritto-buddhismo-thailandia-cash-3618033))

- birch bark = **corteccia di betulla**  (see, e.g., this [usage](https://it.wikipedia.org/wiki/Iscrizioni_novgorodiane_su_corteccia_di_betulla))

**Comment by maieul** [comment]
Ok. So in this case, I will publish like this, and if someone need a translation, (s)he will add it.

**Comment by maieul** [comment]
I didn't see @wujastyk link. So I will add these form,as @doc73 agree with them

**Comment by maieul** [comment]
Send to CTAN. Thanks you both @wujastyk  and @Doc73.

**Comment by Doc73** [comment]
Many thanks to you, @maieul !
