### ISSUE TITLE
pages vs. folios

### ISSUE THREAD

**Issue by wujastyk** [maieul/biblatex-manuscripts-philology#8]
In my field (South Asia) we normally talk about the **foliation** of manuscripts and the **pagination** of books.  Very rarely, a manuscript is paginated (numbering on both obverse and reverse).  I think this terminology is general beyond S. Asian studies.

So the field "pages" doesn't work so well.  It should be "foliation," (or "folios") shouldn't it?

**Comment by maieul** [comment]
I my field too... but we must to be coherent with general system of biblatex. 
It use page/pages field to show the number of physical unity inside a volume. 
The field pagination/bookpagination define which system of mesure is used. By default biblatex provide "page, column, line, verse, section, and paragraph" (cf 2.3.10). biblatex-manuscripts add "foliotation" and set up as default unit for manuscripts. 

At most, we could make "folios" (but not "foliotation") to be an alias for page, but I don't think it is a so good idea, as it will create an exception on general system used by biblatex.

**Comment by maieul** [comment]
My bad: biblatex-manuscripts does not set up "folio" as default unit (and it won't, as it could break compatibility with older file)

**Comment by wujastyk** [comment]
I forked the documentation and made some edits to address this point, followed by a pull request.
